# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end

# TODO: Uncomment on final deployment
=begin
Country.create([
                 { name_en: 'Afghanistan' },
                 { name_en: 'Albania' },
                 { name_en: 'Algeria' },
                 { name_en: 'Andorra' },
                 { name_en: 'Angola' },
                 { name_en: 'Anguilla' },
                 { name_en: 'Antarctica' },
                 { name_en: 'Antigua and Barbuda' },
                 { name_en: 'Argentina' },
                 { name_en: 'Armenia' },
                 { name_en: 'Aruba' },
                 { name_en: 'Australia' },
                 { name_en: 'Austria' },
                 { name_en: 'Azerbaijan' },
                 { name_en: 'Bahamas' },
                 { name_en: 'Bahrain' },
                 { name_en: 'Bangladesh' },
                 { name_en: 'Barbados' },
                 { name_en: 'Belarus' },
                 { name_en: 'Belgium' },
                 { name_en: 'Belize' },
                 { name_en: 'Benin' },
                 { name_en: 'Bermuda' },
                 { name_en: 'Bhutan' },
                 { name_en: 'Bolivia' },
                 { name_en: 'Bonaire' },
                 { name_en: 'Bosnia and Herzegovina' },
                 { name_en: 'Botswana' },
                 { name_en: 'Brazil' },
                 { name_en: 'Brunei' },
                 { name_en: 'Bulgaria' },
                 { name_en: 'Burkina Faso' },
                 { name_en: 'Burundi' },
                 { name_en: 'Cabo Verde' },
                 { name_en: 'Cambodia' },
                 { name_en: 'Cameroon' },
                 { name_en: 'Canada' },
                 { name_en: 'Cayman Islands' },
                 { name_en: 'Central African Republic' },
                 { name_en: 'Chad' },
                 { name_en: 'Chile' },
                 { name_en: 'China' },
                 { name_en: 'Colombia' },
                 { name_en: 'Comoros' },
                 { name_en: 'Congo, Democratic Republic of the' },
                 { name_en: 'Congo, Republic of the' },
                 { name_en: 'Costa Rica' },
                 { name_en: "Côte d’Ivoire" },
                 { name_en: 'Croatia' },
                 { name_en: 'Cuba' },
                 { name_en: 'Curacao' },
                 { name_en: 'Cyprus' },
                 { name_en: 'Czech Republic' },
                 { name_en: 'Denmark' },
                 { name_en: 'Djibouti' },
                 { name_en: 'Dominica' },
                 { name_en: 'Dominican Republic' },
                 { name_en: 'Ecuador' },
                 { name_en: 'Egypt' },
                 { name_en: 'El Salvador' },
                 { name_en: 'England' },
                 { name_en: 'Equatorial Guinea' },
                 { name_en: 'Eritrea' },
                 { name_en: 'Estonia' },
                 { name_en: 'Eswatini' },
                 { name_en: 'Ethiopia' },
                 { name_en: 'Fiji' },
                 { name_en: 'Finland' },
                 { name_en: 'France' },
                 { name_en: 'French Guiana' },
                 { name_en: 'French Polynesia' },
                 { name_en: 'Gabon' },
                 { name_en: 'Gambia' },
                 { name_en: 'Georgia' },
                 { name_en: 'Germany' },
                 { name_en: 'Ghana' },
                 { name_en: 'Gibraltar' },
                 { name_en: 'Greece' },
                 { name_en: 'Greenland' },
                 { name_en: 'Grenada' },
                 { name_en: 'Guadeloupe' },
                 { name_en: 'Guatemala' },
                 { name_en: 'Guinea' },
                 { name_en: 'Guinea-Bissau' },
                 { name_en: 'Guyana' },
                 { name_en: 'Haiti' },
                 { name_en: 'Honduras' },
                 { name_en: 'Hungary' },
                 { name_en: 'Iceland' },
                 { name_en: 'India' },
                 { name_en: 'Indonesia'},
                 { name_en: 'Iran' },
                 { name_en: 'Iraq' },
                 { name_en: 'Ireland' },
                 { name_en: 'Israel' },
                 { name_en: 'Italy' },
                 { name_en: 'Jamaica' },
                 { name_en: 'Japan' },
                 { name_en: 'Jordan' },
                 { name_en: 'Kazakhstan' },
                 { name_en: 'Kenya' },
                 { name_en: 'Kiribati' },
                 { name_en: "Korea, Democratic People's Republic Of" },
                 { name_en: 'Korea, Republic Of' },
                 { name_en: 'Kosovo' },
                 { name_en: 'Kuwait' },
                 { name_en: 'Kyrgyzstan' },
                 { name_en: "Laos" },
                 { name_en: 'Latvia' },
                 { name_en: 'Lebanon' },
                 { name_en: 'Lesotho' },
                 { name_en: 'Liberia' },
                 { name_en: 'Libya' },
                 { name_en: 'Liechtenstein' },
                 { name_en: 'Lithuania' },
                 { name_en: 'Luxembourg' },
                 { name_en: 'Madagascar' },
                 { name_en: 'Malawi' },
                 { name_en: 'Malaysia' },
                 { name_en: 'Maldives' },
                 { name_en: 'Mali' },
                 { name_en: 'Malta' },
                 { name_en: 'Marshall Islands' },
                 { name_en: 'Martinique' },
                 { name_en: 'Mauritania' },
                 { name_en: 'Mauritius' },
                 { name_en: 'Mexico' },
                 { name_en: 'Micronesia, Federated States of' },
                 { name_en: 'Moldova' },
                 { name_en: 'Monaco' },
                 { name_en: 'Mongolia' },
                 { name_en: 'Montenegro' },
                 { name_en: 'Montserrat' },
                 { name_en: 'Morocco' },
                 { name_en: 'Mozambique' },
                 { name_en: 'Myanmar' },
                 { name_en: 'Namibia' },
                 { name_en: 'Nauru' },
                 { name_en: 'Nepal' },
                 { name_en: 'Netherlands' },
                 { name_en: 'New Zealand' },
                 { name_en: 'Nicaragua' },
                 { name_en: 'Niger' },
                 { name_en: 'Nigeria' },
                 { name_en: 'Northern Ireland' },
                 { name_en: 'North Macedonia' },
                 { name_en: 'Norway' },
                 { name_en: 'Oman' },
                 { name_en: 'Pakistan' },
                 { name_en: 'Palau' },
                 { name_en: 'Palestine, The State of' },
                 { name_en: 'Panama' },
                 { name_en: 'Papua New Guinea' },
                 { name_en: 'Paraguay' },
                 { name_en: 'Peru' },
                 { name_en: 'Philippines' },
                 { name_en: 'Poland' },
                 { name_en: 'Portugal' },
                 { name_en: 'Puerto Rico' },
                 { name_en: 'Qatar' },
                 { name_en: 'Romania' },
                 { name_en: 'Russia'},
                 { name_en: 'Rwanda'},
                 { name_en: 'Saint Kitts and Nevis' },
                 { name_en: 'Saint Lucia' },
                 { name_en: 'Saint Martin' },
                 { name_en: 'Saint Vincent and the Grenadines' },
                 { name_en: 'Samoa' },
                 { name_en: 'San Marino' },
                 { name_en: 'Sao Tome and Principe' },
                 { name_en: 'Saudi Arabia' },
                 { name_en: 'Scotland' },
                 { name_en: 'Senegal' },
                 { name_en: 'Serbia' },
                 { name_en: 'Seychelles' },
                 { name_en: 'Sierra Leone' },
                 { name_en: 'Singapore' },
                 { name_en: 'Slovakia' },
                 { name_en: 'Slovenia' },
                 { name_en: 'Solomon Islands' },
                 { name_en: 'Somalia' },
                 { name_en: 'South Africa' },
                 { name_en: 'Spain' },
                 { name_en: 'Sri Lanka' },
                 { name_en: 'Sudan' },
                 { name_en: 'Sudan, South' },
                 { name_en: 'Suriname'},
                 { name_en: 'Sweden'},
                 { name_en: 'Switzerland'},
                 { name_en: 'Syria' },
                 { name_en: 'Taiwan' },
                 { name_en: 'Tajikistan' },
                 { name_en: 'Tanzania' },
                 { name_en: 'Thailand' },
                 { name_en: 'Timor-Leste' },
                 { name_en: 'Togo' },
                 { name_en: 'Tonga' },
                 { name_en: 'Trinidad and Tobago' },
                 { name_en: 'Tunisia' },
                 { name_en: 'Turkey' },
                 { name_en: 'Turkmenistan' },
                 { name_en: 'Turks and Caicos Islands' },
                 { name_en: 'Tuvalu' },
                 { name_en: 'Uganda' },
                 { name_en: 'Ukraine' },
                 { name_en: 'United Arab Emirates' },
                 { name_en: 'United Kingdom' },
                 { name_en: 'United States' },
                 { name_en: 'Uruguay' },
                 { name_en: 'Uzbekistan' },
                 { name_en: 'Vanuatu' },
                 { name_en: 'Vatican City' },
                 { name_en: 'Venezuela'},
                 { name_en: 'Vietnam'},
                 { name_en: 'Virgin Islands, British' },
                 { name_en: 'Virgin Islands, U.S.' },
                 { name_en: 'Wales' },
                 { name_en: 'Yemen' },
                 { name_en: 'Zambia' },
                 { name_en: 'Zimbabwe' }
               ])
=end


# TODO: Uncomment on final deployment
=begin
PropertyType.create([
                      { name: "apartment" },
                      { name: "bungalow" },
                      { name: "cabin" },
                      { name: "condominium" },
                      { name: "cottage" },
                      { name: "detached" },
                      { name: "duplex" },
                      { name: "mansion" },
                      { name: "penthouse" },
                      { name: "quadplex" },
                      { name: "ranch" },
                      { name: "semi-detached" },
                      { name: "single-family" },
                      { name: "tiny" },
                      { name: "townhouse" },
                      { name: "triplex" },
                      { name: "split-level" },
                      { name: "villa" }
                    ])
=end